name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'invalid'
  - 'wontfix'

categories:
  - title: '🛠 Breaking Changes'
    labels:
      - 'breaking-change'
      - 'major'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feature request'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
      - 'dependency'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'bugfix'
      - 'chore'
      - 'maintenance'
      - 'dependencies'
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Say thanks

  <a href="https://www.buymeacoffee.com/hskdk" target="_blank"><img src="https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png" alt="Buy Me A Coffee" style="height: 41px !important;width: 174px !important;box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;-webkit-box-shadow: 0px 3px 2px 0px rgba(190, 190, 190, 0.5) !important;" ></a>

autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/feature/i'
      - '/feat/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/chore/i'
  - label: 'documentation'
    branch:
      - '/docs?\/.+/'
    title:
      - '/docs?/i'
  - label: 'dependencies'
    files:
      - 'requirements.txt'
      - 'custom_components/thermex_api/manifest.json'
    title:
      - '/bump/i'
      - '/update.*dependency/i'
