# Home Assistant Test Script for Delayed Turn-Off
# Add this to your automations.yaml or use it in the Developer Tools -> Services

# Test 1: Check if the fan is running
# Go to Developer Tools -> States and look for:
# - fan.YOUR_DEVICE_ID_fan (should show is_on: true)

# Test 2: Call the delayed turn-off service
# Go to Developer Tools -> Services and call:
# Service: thermex_api.start_delayed_off
# Entity ID: fan.YOUR_DEVICE_ID_fan

# Test 3: Check the sensor
# Look for sensor.YOUR_DEVICE_ID_delayed_turn_off_time
# It should show a timestamp 2 minutes in the future

# Test 4: Check fan attributes
# Look at the fan entity attributes for:
# - delayed_off_active: true
# - delayed_off_remaining: 2
# - delayed_off_scheduled_time: (ISO timestamp)

# Test 5: Check the logs
# Go to Configuration -> Logs and filter for "thermex"
# You should see messages like:
# "DelayedTurnOffButton pressed - calling start_delayed_off service"
# "start_delayed_off service called"
# "DEBUG: Using 2 minutes for delayed turn-off"
# "Starting delayed turn-off: 2 minutes (until HH:MM)"

# After 2 minutes, you should see:
# "Executing delayed turn-off - fan should turn off now"
# "Delayed turn-off completed and state cleared"

# Alternative: Use this automation to test
automation:
  - alias: "Test Thermex Delayed Turn-Off"
    trigger:
      - platform: state
        entity_id: input_boolean.test_thermex_delay  # Create this helper first
        to: "on"
    action:
      - service: thermex_api.start_delayed_off
        target:
          entity_id: fan.YOUR_DEVICE_ID_fan  # Replace with your actual fan entity ID
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.test_thermex_delay
