update_light:
  description: Update the light settings.
  fields:
    lightonoff:
      description: Whether to turn the light on(1) or off(1).
      example: 1
      required: true
      type: integer
    brightness:
      description: The brightness level of the light.
      example: 50
      required: true
      type: integer

update_fan:
  description: Update the fan settings.
  fields:
    fanonoff:
      description: Whether to turn the fan on(1) or off(0).
      example: 1
      required: true
      type: integer
    fanspeed:
      description: The speed of the fan (1-4).
      example: 3
      required: true
      type: integer
