name: "Release"

on:
  release:
    types: ["published"]

jobs:
  update_hacs_manifest:
    name: "Prepare release asset"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"

      - name: "Get version"
        id: "version"
        uses: "home-assistant/actions/helpers/version@master"

      - name: "Set manifest version number"
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py \
            --version ${{ steps.version.outputs.version }}

      - name: "Create zip"
        run: |
          cd custom_components/thermex_api
          zip thermex_api.zip -r ./

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.11.2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: "./custom_components/thermex_api/thermex_api.zip"
          asset_name: "thermex_api.zip"
          tag: "${{ github.ref }}"
          overwrite: true
